### ISSUE TITLE
Translation of Attribute descriptions

### ISSUE THREAD

**Issue by fvakiliev** [DigitalFlow/Xrm-Quick-Edit#17]
How to translate an Attribute description text?

**Comment by DigitalFlow** [comment]
Hey there,

Descriptions are not yet implemented.
However I already thought about that, I could add this option as a new configuration dropdown.
It should not take that much time to implement, will add it soon.

**Comment by fvakiliev** [comment]
Many thanks! I'll wait with impatience!
FV

**Comment by DigitalFlow** [comment]
Hey there,

I just released v2.7.0, with this release you can choose, which component you want to translate.
This is only for entities and attributes right now, where you can choose between display name and description.

Kind Regards,
Florian

**Comment by fvakiliev** [comment]
Hi Florian!

Works fine! Many thanks.

Regards,
Firat
