### ISSUE TITLE
Can not import Xrm-Quick-Edit managed solution

### ISSUE THREAD

**Issue by fvakiliev** [DigitalFlow/Xrm-Quick-Edit#19]
Hi Florian,

I can't import _Xrm-Quick-Edit_ managed solution Release v2.8.0 with error message:

> You can only import solutions with a package version of 8.2 or earlier into this organization. Also, you can't import any solutions into this organization that were exported from Microsoft Dynamics 365 2011 or earlier.

My environment:
- MS Dynamics 365 v8.2.2.112 on-premises
- Xrm-Quick-Edit managed solution Release v2.7.0

Regards,
OldCat

**Comment by DigitalFlow** [comment]
Hi Firat,

sorry, this is because I only have a CRM v9 organization for developing right now, therefore Release v2.7.0 is a >= v9 solution.
I'll try releasing a CRM v8 solution as well as soon as possible.

Kind Regards,
Florian

**Comment by fvakiliev** [comment]
Hi Florian!

I think that you could export the solution for **both** version 9.0 and 8.2 (exporting from 9.0 allows this). Spread on git four files of solutions.

Regards,
OldCat

**Comment by DigitalFlow** [comment]
@fvakiliev:
V3.0.0 supports CRM >= 2016 again.

Kind Regards,
Florian
