### ISSUE TITLE
Solution support

### ISSUE THREAD

**Issue by lar-mar** [DigitalFlow/Xrm-Quick-Edit#24]
Hi Florian,
it would be great if we would have the possibility while maintaining the translations to select a solution so that the adjusted attributes, views, etc. are automatically added to that solution.
Typically key users maintain the translation but they are not familiar with adding the necessary components to a solution. As we want to deploy only changes instead of the whole bunch it is not so easy to determine the changes a key user did while translating.

cheers
Lars

**Comment by DigitalFlow** [comment]
Implemented in 6a39c33484e9e4db042d8e8c6ef456cdaad4449b, released in v3.6.0
