### ISSUE TITLE
Optionset item cannot be added to the solution because root component option set is missing

### ISSUE THREAD

**Issue by lar-mar** [DigitalFlow/Xrm-Quick-Edit#33]
When I translate the optionsets and try to save them so that they are added to the configured solution automatically I get an error:
![image](https://user-images.githubusercontent.com/15412588/72978825-69c4f580-3dd7-11ea-8dac-e81429b6c0a0.png)

**Comment by lar-mar** [comment]
Issues still exists in 3.8.0:
![image](https://user-images.githubusercontent.com/15412588/77778280-0c585980-7051-11ea-9949-fdf68737d6fa.png)

**Comment by DigitalFlow** [comment]
Fixed in v3.8.1, please check.

**Comment by lar-mar** [comment]
I can confirm, behavior is fixed in 3.8.1.
Thanks a lot.
